#!/bin/bash
BASE_DIR="${PWD}"
CHECKOUT_DIR='project-git'
DIST_DIR='project-dist'
VERSION="$(cat "${BASE_DIR}/version/version")"
source "${CHECKOUT_DIR}/ci/common/scripts/lib.sh"


export SETUPTOOLS_SCM_PRETEND_VERSION

# inject version since .git will not be pushed
SETUPTOOLS_SCM_PRETEND_VERSION=$(tr -d '-' <<< "${VERSION}")
echo "$VERSION" > "${CHECKOUT_DIR}/.version"

# When deploying in editable mode, version must ultimately appear in
# PKG_INFO as generated by `python setup.py egg_info`.

mv "${BASE_DIR}/${CHECKOUT_DIR}"/{,.[!.]}* "${BASE_DIR}/${DIST_DIR}/"

exit 0
