platform: linux

image_resource:
  type: docker-image
  source:
    repository: python

inputs:
  - name: project-git
  - name: version

outputs:
  - name: project-dist

run:
  path: project-git/ci/common/tasks/python-prep-push.sh