# https://github.com/cathive/concourse-sonarqube-qualitygate-task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-qualitygate-task
    tag: latest # Use one of the versioned tags for reproducible builds!

inputs:
- name: code-analysis

run:
  path: /sonarqube-qualitygate-check
  dir: code-analysis